### ISSUE TITLE
es6 issue

### ISSUE THREAD

**Issue by ajpaul** [jmcooper/ng2-fundamentals#1]
Every time I pull down this project and run `npm install` and then `npm start` I get an unexpected token syntax error on `node_modules/ng2f-server/passport.js:9` when it hits the first ES6 arrow function.

**Comment by ajpaul** [comment]
Argh...I had nvm swap my node versions down. Perhaps you could add something to the readme to make sure you're running a nodejs version > 4.4.5

**Comment by jmcooper** [comment]
Thanks @ajpaul adding that to the readme is a good idea. It's mentioned in the course, but that's easily missed by skipping that clip (understanding that skipping around is not unusual).
