### ISSUE TITLE
404 error / undefined

### ISSUE THREAD

**Issue by behsayah** [jmcooper/ng2-fundamentals#13]
I'm getting following error in VS Code terminal:
**404 error / undefined**
and the following error in browser's console:
**Failed to load resource: the server responded with a status of 404 (Not Found)**

FYI, I did not add anything to the project. Just install npm and add main.ts and run the project. 
I'm running it in my mac. Could you please help me to fix the issue>

**Comment by joeeames** [comment]
please post in the discussion forum for the course.
