### ISSUE TITLE
npm WARN ng2-fundamentals-demo@1.0.0 No license field.

### ISSUE THREAD

**Issue by khawajaasim** [jmcooper/ng2-fundamentals#14]
Hi,
I am new to node and angular and I am taking your course from pluralsight.
I am getting this error when I finish cloning your repository and tries to run command **npm install**
It says something like this 
**npm WARN ng2-fundamentals-demo@1.0.0 No license field.**

can you please help?

**Comment by joeeames** [comment]
it's a warning. not an error. it's not important. ignore it.
