### ISSUE TITLE
Get error when trying to issue the command npm start

### ISSUE THREAD

**Issue by vurso** [jmcooper/ng2-fundamentals#15]
Hi,

Tried to follow the steps in the Pluralsight course Angular 2 Fundamentals however when I get to the step to issue the command npm start I get a series of errors, the first one being:

Error occured when executing command: npm run tsc:w
 Error: Unable to detect platform shell type. Please set SHELL_EXECUTE_FLAGS env variable.

I am running the latest version of Windows 10 Professional 64 bit, installed nvm as per the video guide and install node.js via npm.

Below is the log file dump:

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'start' ]
> 2 info using npm@3.10.3
> 3 info using node@v6.3.0
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle ng2-fundamentals-demo@1.0.0~prestart: ng2-fundamentals-demo@1.0.0
> 6 silly lifecycle ng2-fundamentals-demo@1.0.0~prestart: no script for prestart, continuing
> 7 info lifecycle ng2-fundamentals-demo@1.0.0~start: ng2-fundamentals-demo@1.0.0
> 8 verbose lifecycle ng2-fundamentals-demo@1.0.0~start: unsafe-perm in lifecycle true
> 9 verbose lifecycle ng2-fundamentals-demo@1.0.0~start: PATH: C:\Users\xxxxxxxx\AppData\Roaming\nvm\v6.3.0\node_modules\npm\bin\node-gyp-bin;C:\Projects\Learning\ng2-fundamentals\node_modules\.bin;C:\Program Files\nodejs;C:\Users\xxxxxxxx\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\xxxxxxxxxx\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn;C:\Program Files\Microsoft SQL Server\100\Tools\Binn;C:\Program Files\Microsoft SQL Server\100\DTS\Binn;C:\Program Files (x86)\NoteBook FanControl;C:\Program Files\dotnet;C:\Users\xxxxxxxxxx\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Users\xxxxxxxx\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\cygwin64\bin;C:\Users\xxxxxxx\AppData\Roaming\npm;C:\Users\xxxxxxxxxx\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
> 10 verbose lifecycle ng2-fundamentals-demo@1.0.0~start: CWD: C:\Projects\Learning\ng2-fundamentals
> 11 silly lifecycle ng2-fundamentals-demo@1.0.0~start: Args: [ '/d /s /c',
> 11 silly lifecycle   'tsc && concurrently "npm run tsc:w" "npm run server" ' ]
> 12 silly lifecycle ng2-fundamentals-demo@1.0.0~start: Returned: code: 1  signal: null
> 13 info lifecycle ng2-fundamentals-demo@1.0.0~start: Failed to exec start script
> 14 verbose stack Error: ng2-fundamentals-demo@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run server" `
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (C:\Users\xxxxxxxx\AppData\Roaming\nvm\v6.3.0\node_modules\npm\lib\utils\lifecycle.js:242:16)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at EventEmitter.emit (events.js:191:7)
> 14 verbose stack     at ChildProcess.<anonymous> (C:\Users\xxxxxxx\AppData\Roaming\nvm\v6.3.0\node_modules\npm\lib\utils\spawn.js:40:14)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at ChildProcess.emit (events.js:191:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:852:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
> 15 verbose pkgid ng2-fundamentals-demo@1.0.0
> 16 verbose cwd C:\Projects\Learning\ng2-fundamentals
> 17 error Windows_NT 10.0.15063
> 18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
> 19 error node v6.3.0
> 20 error npm  v3.10.3
> 21 error code ELIFECYCLE
> 22 error ng2-fundamentals-demo@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run server" `
> 22 error Exit status 1
> 23 error Failed at the ng2-fundamentals-demo@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run server" '.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the ng2-fundamentals-demo package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     tsc && concurrently "npm run tsc:w" "npm run server"
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs ng2-fundamentals-demo
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls ng2-fundamentals-demo
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]
>

**Comment by luke80** [comment]
Similar issue, same operating system. I have updated/installed (Direction followed and checked: Make sure you have the latest version of node.js and npm installed.)

Output from ```ng -v```
```code
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.6
node: 6.10.0
os: win32 x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.6
```

Is this perhaps related to https://github.com/kimmobrunfeldt/concurrently/issues/60

My command line output:
```code
$ npm start

> ng2-fundamentals-demo@1.0.0 start C:\Apache24\htdocs\GitHub\ng2-fundamentals
> tsc && concurrently "npm run tsc:w" "npm run server"

 Error occured when executing command: npm run tsc:w
 Error: Unable to detect platform shell type. Please set SHELL_EXECUTE_FLAGS env variable.
     at detectExecuteFlags (C:\Apache24\htdocs\GitHub\ng2-fundamentals\node_modules\spawn-default-shell\src\get-shell.js:29:9)
     at getShell (C:\Apache24\htdocs\GitHub\ng2-fundamentals\node_modules\spawn-default-shell\src\get-shell.js:37:19)
     at Object.spawn (C:\Apache24\htdocs\GitHub\ng2-fundamentals\node_modules\spawn-default-shell\src\index.js:5:24)
     at C:\Apache24\htdocs\GitHub\ng2-fundamentals\node_modules\concurrently\src\main.js:195:34
     at arrayMap (C:\Apache24\htdocs\GitHub\ng2-fundamentals\node_modules\lodash\lodash.js:660:23)
     at Function.map (C:\Apache24\htdocs\GitHub\ng2-fundamentals\node_modules\lodash\lodash.js:9571:14)
     at run (C:\Apache24\htdocs\GitHub\ng2-fundamentals\node_modules\concurrently\src\main.js:181:22)
     at main (C:\Apache24\htdocs\GitHub\ng2-fundamentals\node_modules\concurrently\src\main.js:61:5)
     at Object.<anonymous> (C:\Apache24\htdocs\GitHub\ng2-fundamentals\node_modules\concurrently\src\main.js:424:1)
     at Module._compile (module.js:570:32)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ng2-fundamentals-demo@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run server" `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng2-fundamentals-demo@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-fundamentals-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm run tsc:w" "npm run server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-fundamentals-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-fundamentals-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Apache24\htdocs\GitHub\ng2-fundamentals\npm-debug.log
```

**Comment by vurso** [comment]
Resolved this please see my answer here on slack:

https://stackoverflow.com/questions/34335340/angular2-quickstart-npm-start-is-not-working-correctly/44228456#44228456
