### ISSUE TITLE
HI i my application is not start i have some issue please check it 

### ISSUE THREAD

**Issue by rohitazad** [jmcooper/ng2-fundamentals#20]
I m view to this https://app.pluralsight.com/library/courses/angular-fundamentals/table-of-contents video and i see to 60 video 
but i have face to this issue.

hi i m type to this commond 
npm start 

F:\Practice\ng\ng-2\3\4>npm start

> ng2-fundamentals-demo@1.0.0 start F:\Practice\ng\ng-2\3\4
> tsc && concurrently "npm run tsc:w" "npm run server"

app/events/shared/event.service.ts(10,5): error TS2322: Type 'Subject<IEvent[]>'
 is not assignable to type 'Observable<IEvent[]>'.
  Types of property 'lift' are incompatible.
    Type '<T, R>(operator: Operator<T, R>) => Observable<T>' is not assignable t
o type '<R>(operator: Operator<IEvent[], R>) => Observable<R>'.
      Type 'Observable<IEvent[]>' is not assignable to type 'Observable<R>'.
        Type 'IEvent[]' is not assignable to type 'R'.
app/events/shared/event.service.ts(13,19): error TS2339: Property 'find' does no
t exist on type 'IEvent[]'.
app/events/shared/event.service.ts(23,24): error TS2339: Property 'findIndex' do
es not exist on type 'IEvent[]'.
node_modules/@angular/core/src/facade/lang.d.ts(12,17): error TS2693: 'Map' only
 refers to a type, but is being used as a value here.
node_modules/@angular/core/src/facade/lang.d.ts(13,17): error TS2693: 'Set' only
 refers to a type, but is being used as a value here.
node_modules/@types/core-js/index.d.ts(47,36): error TS2304: Cannot find name 'I
terable'.
node_modules/@types/core-js/index.d.ts(353,48): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(354,52): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(355,34): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(356,34): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(357,34): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(358,61): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(359,60): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(360,65): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(360,97): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(361,60): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(362,58): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(363,59): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(364,58): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(365,61): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(365,117): error TS2304: Cannot find name
'PropertyKey'.
node_modules/@types/core-js/index.d.ts(366,42): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(368,81): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(369,78): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(370,76): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(371,73): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(434,6): error TS2304: Cannot find name 'S
ymbol'.
node_modules/@types/core-js/index.d.ts(467,59): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(468,59): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(470,48): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(471,69): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(475,40): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(477,48): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(693,55): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(694,45): error TS2304: Cannot find name '
PropertyKey'.
node_modules/@types/core-js/index.d.ts(710,46): error TS2304: Cannot find name '
Iterable'.
node_modules/@types/core-js/index.d.ts(711,43): error TS2304: Cannot find name '
Iterable'.
node_modules/@types/core-js/index.d.ts(826,20): error TS2304: Cannot find name '
PromiseConstructor'.
node_modules/@types/core-js/index.d.ts(841,32): error TS2304: Cannot find name '
Iterable'.
node_modules/@types/core-js/index.d.ts(845,39): error TS2304: Cannot find name '
Iterable'.
node_modules/@types/core-js/index.d.ts(845,53): error TS2304: Cannot find name '
Iterator'.
node_modules/@types/core-js/index.d.ts(1479,36): error TS2339: Property 'for' do
es not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1483,43): error TS2339: Property 'hasInst
ance' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1487,50): error TS2339: Property 'isConca
tSpreadable' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1491,40): error TS2339: Property 'iterato
r' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1495,38): error TS2339: Property 'keyFor'
 does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1499,37): error TS2339: Property 'match'
does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1503,39): error TS2339: Property 'replace
' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1507,38): error TS2339: Property 'search'
 does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1511,39): error TS2339: Property 'species
' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1515,37): error TS2339: Property 'split'
does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1519,43): error TS2339: Property 'toPrimi
tive' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1523,43): error TS2339: Property 'toStrin
gTag' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1527,43): error TS2339: Property 'unscopa
bles' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2294,36): error TS2339: Property 'for' do
es not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2298,43): error TS2339: Property 'hasInst
ance' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2302,50): error TS2339: Property 'isConca
tSpreadable' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2306,40): error TS2339: Property 'iterato
r' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2310,38): error TS2339: Property 'keyFor'
 does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2314,37): error TS2339: Property 'match'
does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2318,39): error TS2339: Property 'replace
' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2322,38): error TS2339: Property 'search'
 does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2326,39): error TS2339: Property 'species
' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2330,37): error TS2339: Property 'split'
does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2334,43): error TS2339: Property 'toPrimi
tive' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2338,43): error TS2339: Property 'toStrin
gTag' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2342,43): error TS2339: Property 'unscopa
bles' does not exist on type 'SymbolConstructor'.
node_modules/rxjs/Observable.d.ts(66,60): error TS2693: 'Promise' only refers to
 a type, but is being used as a value here.
node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrec
tly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<T, R>(operator: Operator<T, R>) => Observable<T>' is not assignable t
o type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
node_modules/rxjs/observable/dom/WebSocketSubject.d.ts(23,22): error TS2415: Cla
ss 'WebSocketSubject<T>' incorrectly extends base class 'AnonymousSubject<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => WebSocketSubject<R>' is not assignabl
e to type '<T, R>(operator: Operator<T, R>) => Observable<T>'.
      Type 'WebSocketSubject<R>' is not assignable to type 'Observable<T>'.
        Types of property 'operator' are incompatible.
          Type 'Operator<any, R>' is not assignable to type 'Operator<any, T>'.
            Type 'R' is not assignable to type 'T'.
node_modules/rxjs/operator/toPromise.d.ts(7,59): error TS2693: 'Promise' only re
fers to a type, but is being used as a value here.
node_modules/rxjs/operator/toPromise.d.ts(10,26): error TS2693: 'Promise' only r
efers to a type, but is being used as a value here.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ng2-fundamentals-demo@1.0.0 start: `tsc && concurrently "npm run tsc:w"
 "npm run server" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ng2-fundamentals-demo@1.0.0 start script 'tsc && concurre
ntly "npm run tsc:w" "npm run server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-fundamentals-demo
 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm run tsc:w" "npm run server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-fundamentals-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-fundamentals-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Practice\ng\ng-2\3\4\npm-debug.log

NPM-debug.log file is 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ng2-fundamentals-demo@1.0.0~prestart: ng2-fundamentals-demo@1.0.0
6 silly lifecycle ng2-fundamentals-demo@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle ng2-fundamentals-demo@1.0.0~start: ng2-fundamentals-demo@1.0.0
8 verbose lifecycle ng2-fundamentals-demo@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle ng2-fundamentals-demo@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;F:\Practice\ng\ng-2\3\4\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\Users\rohit.azad\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin
10 verbose lifecycle ng2-fundamentals-demo@1.0.0~start: CWD: F:\Practice\ng\ng-2\3\4
11 silly lifecycle ng2-fundamentals-demo@1.0.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'tsc && concurrently "npm run tsc:w" "npm run server" ' ]
12 silly lifecycle ng2-fundamentals-demo@1.0.0~start: Returned: code: 2  signal: null
13 info lifecycle ng2-fundamentals-demo@1.0.0~start: Failed to exec start script
14 verbose stack Error: ng2-fundamentals-demo@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run server" `
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ng2-fundamentals-demo@1.0.0
16 verbose cwd F:\Practice\ng\ng-2\3\4
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error ng2-fundamentals-demo@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run server" `
22 error Exit status 2
23 error Failed at the ng2-fundamentals-demo@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run server" '.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ng2-fundamentals-demo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc && concurrently "npm run tsc:w" "npm run server"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ng2-fundamentals-demo
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ng2-fundamentals-demo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by joeeames** [comment]
looks like some kind of typing issue maybe. Not sure.  Try using a checkpoint of the code maybe. I've had similar issues and they're always tough to troubleshoot.

**Comment by rohitazad** [comment]
@joeeames  thanks for reply i resolve to my issue 👍
