### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by zavakare** [jmcooper/ng2-fundamentals#21]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.3
3 info using node@v6.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ng2-fundamentals-demo@1.0.0~prestart: ng2-fundamentals-demo@1.0.0
6 silly lifecycle ng2-fundamentals-demo@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle ng2-fundamentals-demo@1.0.0~start: ng2-fundamentals-demo@1.0.0
8 verbose lifecycle ng2-fundamentals-demo@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle ng2-fundamentals-demo@1.0.0~start: PATH: C:\Users\Karen\AppData\Roaming\nvm\v6.3.0\node_modules\npm\bin\node-gyp-bin;C:\Users\Karen\Desktop\AngularFundamentals\ng2-fundamentals\node_modules\.bin;C:\Program Files\nodejs;C:\Users\Karen\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Karen\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Hewlett-Packard\SimplePass;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\dotnet;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio;C:\Program Files\Git\cmd;C:\Users\Karen\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\nodejs;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Karen\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\Karen\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle ng2-fundamentals-demo@1.0.0~start: CWD: C:\Users\Karen\Desktop\AngularFundamentals\ng2-fundamentals
11 silly lifecycle ng2-fundamentals-demo@1.0.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'tsc && concurrently "npm run tsc:w" "npm run server" ' ]
12 silly lifecycle ng2-fundamentals-demo@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle ng2-fundamentals-demo@1.0.0~start: Failed to exec start script
14 verbose stack Error: ng2-fundamentals-demo@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run server" `
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Karen\AppData\Roaming\nvm\v6.3.0\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Karen\AppData\Roaming\nvm\v6.3.0\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid ng2-fundamentals-demo@1.0.0
16 verbose cwd C:\Users\Karen\Desktop\AngularFundamentals\ng2-fundamentals
17 error Windows_NT 6.2.9200
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.3.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error ng2-fundamentals-demo@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run server" `
22 error Exit status 1
23 error Failed at the ng2-fundamentals-demo@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run server" '.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ng2-fundamentals-demo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc && concurrently "npm run tsc:w" "npm run server"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ng2-fundamentals-demo
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ng2-fundamentals-demo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

NPM VERSION :
$ npm version
{ 'ng2-fundamentals-demo': '1.0.0',
  npm: '3.10.3',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.3.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.52',
  zlib: '1.2.8' }

What could this be?

**Comment by evidnn** [comment]
I've been able to resolve server start error by calling server.js explicitly. 
If you'll check package.json "npm start" should start the server.js:
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run server\" ",
    "server": "node node_modules/ng2f-server/server.js",
However in my case it failed with the similar error...
Using Git Bash change to the ng2-fundamentals location (in my case it is c:/dev/) and call server.js directly:
cd c:/dev/ng2-fundamentals
node node_modules/ng2f-server/server.js

Hope this helps.

**Comment by kimballjohnson** [comment]
In an npm environment, 'call server.js directly' is ambiguous.
What exactly are you suggesting a developer should do after navigating into the ng2f-server folder?
Thanks

**Comment by BrianGLink** [comment]
evidnn - brilliant! That worked for me!

**Comment by jim-cooper** [comment]
There are also a number of recommendations here for people experiencing this issue: https://github.com/angular/angular/issues/6097
