### ISSUE TITLE
ERRORs galore installing demo - earlier threads, no fixes work

### ISSUE THREAD

**Issue by BrianGLink** [jmcooper/ng2-fundamentals#23]
[npm-debug.log](https://github.com/jmcooper/ng2-fundamentals/files/1335368/npm-debug.log)
I apologize because there have been discussions about this earlier, but none of the fixes have worked for me, and am hoping to scare up some new ideas or at least troubleshooting tips. 

Windows 10, following the Pluralsight course, everything installs, but when I run npm start, I get as far as
```
> ng2-fundamentals-demo@1.0.0 start C:\<my directory>\ng2-fundamentals
> tsc && concurrently "npm run tsc:w" "npm run server"
```

And then the screen lights up with errors, and I can get no further. Tried replacing the double ampersands with one, changing the version numbers in the various json files, uninstalling and reinstalling basically everything. No luck.

Really hoping to be able to follow along - I'm recently unemployed, and getting back into the market, it seems that Angular is de rigeur nowadays. I have little exposure to json or anything beyond the most rudimentary javascript, so my ability to diagnose this myself is quite limited. 

I could just watch the videos, but actually typing stuff out myself has been the best way to really absorb new material.

Thanks for any help.

**Comment by BrianGLink** [comment]
This was solved for me by another poster. I started the server explicitly by running server.js from git-bash. Voila!

**Comment by joeeames** [comment]
running the server directly like that can make things easier, but you want to make sure of a couple things. you also want to be watching your typescript files and recompiling them. so running "npm run tsc:w" in another terminal is a good idea.

personally I don't like concurrently and I never use it myself. I just use multiple terminal windows.

**Comment by jim-cooper** [comment]
There are also a number of recommendations here for people experiencing this issue: angular/angular#6097
