### ISSUE TITLE
Server script syntax error

### ISSUE THREAD

**Issue by codiddle** [jmcooper/ng2-fundamentals#4]
I ran into an issue when following tutorial today on Windows 10.  
These are the versions of node and npm I'm using, taken from the debug log. 

2 info using npm@3.10.3
3 info using node@v6.3.0

I was able to get the server started by changing the syntax slightly:
"start": "tsc && concurrently \"npm run tsc:w\" \"npm run server\" ",
to
"start": "tsc & concurrently \"npm run tsc:w\" \"npm run server\" ",

There is a page full of errors after the script runs, however, it seems to be running ok.

![image](https://cloud.githubusercontent.com/assets/2908061/23824806/7dcd06ec-064b-11e7-9f0d-77e48a4ac181.png)
![image](https://cloud.githubusercontent.com/assets/2908061/23824810/89978074-064b-11e7-9b3b-c946b71dfecf.png)

**Comment by CybrZr00** [comment]
Same problem on Windows 10, same versions.  Workaround worked for me also, and produced the same results.  Glad that these issues have been posted with workarounds!

**Comment by joeeames** [comment]
likely actually this issue:
https://github.com/jmcooper/ng2-fundamentals/issues/3

Please verify.

**Comment by joeeames** [comment]
It's 99.99% chance the issue referenced above, so I'm going to close this issue.

**Comment by codiddle** [comment]
For sure, I was curious if the issue was with TypeScript itself. I haven't got a chance to test, work is busy and all, I will try to make time tomorrow.  Thanks for all you do Joe Eames.

**Comment by joeeames** [comment]
Awesome. I did more research. So basically, the @types/core-js library has some duplicate type definitions that are included in some other library (the base typescript I believe). They considered this to be a bug, so they removed those duplicate definitions. But if you're using the older version of TypeScript (which we are) then it breaks because the older version of typescript doesn't have those definitions. We pinned to the older version of typescript because they break stuff all the time with Angular. 4.1 doesn't work with Angular 2.  Version 4 of Angular 2 works with typescript 4.2, but I don't think it works with version 2 of Angular. Anyway, it's always simpler to just pin stuff to an exact version. We thought we were safe allowing bug fixes, but what they considered to be a bug fix turned out to be a breaking change for the other versions of the libraries we're using. Long explanation, but there it is. Good luck!

**Comment by joeeames** [comment]
And thanks to @petebacondarwin for discovering the underlying cause.

**Comment by rahulsingh9096806080** [comment]
Hi team,
i am facing issues while starting server
$ npm start

> ng2-fundamentals-demo@1.0.0 start D:\A1\ng2-fundamentals
> tsc && concurrently "npm run tsc:w" "npm run server"


npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! file C:\Windows\system32\cmd.exe;
npm ERR! path C:\Windows\system32\cmd.exe;
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Windows\system32\cmd.exe;
npm ERR! ng2-fundamentals-demo@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run server" `
npm ERR! spawn C:\Windows\system32\cmd.exe; ENOENT
npm ERR!
npm ERR! Failed at the ng2-fundamentals-demo@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-fundamentals-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm run tsc:w" "npm run server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-fundamentals-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-fundamentals-demo
npm ERR! There is likely additional logging output above.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! ng2-fundamentals-demo@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run server" `
npm ERR! Exit status -4058
npm ERR!
npm ERR! Failed at the ng2-fundamentals-demo@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-fundamentals-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm run tsc:w" "npm run server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-fundamentals-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-fundamentals-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\A1\ng2-fundamentals\npm-debug.log

**Comment by atentis** [comment]
@rahulsingh9096806080 Did you get this to work? I have spent hours on it with no luck

**Comment by codiddle** [comment]
yeah, i did.  i followed the explicit instructions provided by Eames without listening to other's suggestions and it worked ok.

**Comment by codiddle** [comment]
or Eames, i forget which posted

Cody Christian
Software Developer

On Jun 12, 2017 7:52 PM, "Cody James Christian" <codiddle@gmail.com> wrote:

yeah, i did.  i followed the explicit instructions provided by Cooper
without listening to other's suggestions and it worked ok.

Cody Christian
Software Developer

**Comment by codiddle** [comment]
follow this thread, it will help https://github.com/jmcooper/ng2-fundamentals/issues/3

**Comment by atentis** [comment]
@codiddle Thanks. Changing the angular core version didnt work for me. I reread his response here and decided to just asterisk out the libraries in the package.json... It worked!

**Comment by BrianGLink** [comment]
I'm a .NET guy new to npm and json, and have run into the same issue named above. I've tried all the listed fixes in various combinations and still am having no luck. Is there a definitive fix? I've also been following the related thread [here](https://github.com/jmcooper/ng2-fundamentals/issues/3). 

I'm attaching my debug.log. Thanks for any ideas. 

[npm-debug.log](https://github.com/jmcooper/ng2-fundamentals/files/1331186/npm-debug.log)
