### ISSUE TITLE
when I run npm run tsc

### ISSUE THREAD

**Issue by kevraja** [jmcooper/ng2-fundamentals#5]
![image](https://cloud.githubusercontent.com/assets/26458977/23994311/60a5d2a4-0a12-11e7-8c55-c65cf29166b2.png)

**Comment by kevraja** [comment]
Could you please help me out?

**Comment by joeeames** [comment]
likely solved with the solution to this issue:
https://github.com/jmcooper/ng2-fundamentals/issues/3

Please verify so I can close this issue

**Comment by kevraja** [comment]
fresh clone and npm install works.

**Comment by kevraja** [comment]
Thanks, you can close this issue.
