### ISSUE TITLE
toastr not working

### ISSUE THREAD

**Issue by kevraja** [jmcooper/ng2-fundamentals#6]
import { Component, OnInit } from '@angular/core';
import { EventService } from './shared/event.service'
import {ToastrService} from "../common/toastr.service";

```
@Component({
    selector:'events-list',
    template:`
    <div>
      `<h1>Upcoming` Angular 2 events</h1>
        <hr/>
            <div class="row">
                <div *ngFor="let event of events" class="col-md-5">
                    <event-thumbnail (click) = "handleThumbnailClick(event.name)" [event]="event"></event-thumbnail>
                </div>
            </div>
    </div> 
    
`
```
})

export class EventListComponent implements OnInit{
    events: any[];
    constructor(private eventService: EventService, private toastr: ToastrService){

    }

    ngOnInit(){
        this.events = this.eventService.getEvents();

    }
    handleThumbnailClick(eventName){
        this.toastr.success(eventName);
    }
}

------------------------------------------------------

import { Injectable } from '@angular/core';

declare let toastr:any;

@Injectable()
export class ToastrService{
    success(message: string, title?: string){
        toastr.success(message, title);
    }

    info(message: string, title?: string){
        toastr.info(message, title);
    }

    warning(message: string, title?: string){
        toastr.warning(message, title);
    }

    error(message: string, title?: string){
        toastr.error(message, title);
    }
}
_________________________________________________________________

![image](https://cloud.githubusercontent.com/assets/26458977/24085837/1a2e1e0a-0cd1-11e7-8c6f-9ba4457b87e6.png)

**Comment by kevraja** [comment]
could anyone help on this?

**Comment by jmcooper** [comment]
Can you tell me what version of toastr got installed?

**Comment by kevraja** [comment]
"toastr": "^2.1.2",    @jmcooper

**Comment by Narjes22** [comment]
I have the same problem !

**Comment by Narjes22** [comment]
I have the same problem !

**Comment by kevraja** [comment]
any idea on this? @joeeames

**Comment by joeeames** [comment]
no, not really.....

**Comment by jmcooper** [comment]
Do you have any TypeScript compilation errors? If you look in your terminal/console window after you start the server you can see if your TypeScript is compiling correctly.

**Comment by jmcooper** [comment]
Oh! I just noticed you have some extra tick marks in your html so the parsing of the component is not working. Notice you have four backticks in the template. Remove the ones around `<h1>Upcoming`.

**Comment by kevraja** [comment]
thanks @jmcooper
